[package]
name = "solana-remote-wallet"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
description = "Solana Remote Wallet (stubbed for Termux)"
license = { workspace = true }

[dependencies]
solana-sdk = { workspace = true }
thiserror = "1.0"
uriparse = "0.6"

[features]
default = []

[[bin]]
name = "solana-ledger-udev"
path = "src/bin/ledger-udev.rs"