name: Publish Termux Binaries to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Termux Binaries"]
    types:
      - completed

jobs:
  deploy-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🔽 Download artifact from previous job
        uses: actions/download-artifact@v4
        with:
          name: solana-termux-binaries
          path: pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: 🚀 Push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
          publish_branch: gh-pages